import Vue from 'vue';

import CtmModal from '~/components/CtmModal';
import Loader from '~/components/ui/Loader';
import BaseButton from '~/components/ui/BaseButton';
import BaseInput from '~/components/ui/BaseInput';
import BaseDD from '~/components/ui/BaseDD';
import BaseCheckbox from '~/components/ui/BaseCheckbox';
import BasePager from '~/components/ui/BasePager';
import SearchFilterField from '~/components/SearchFilterField/index.vue';
import Overview from '~/components/Overview';
import MoreInfo from '~/components/MoreInfo';
import TableTxs from '~/components/TableTxs';
import TableTokens from '~/components/TableTokens';
import TableBlocks from '~/components/TableBlocks';
import InfoItem from '~/components/InfoItem';
import EmptyData from '~/components/ui/EmptyData';
import ContractInfo from '~/components/ContractInfo';
import ContractInput from '~/components/ui/ContractInput';
import ButtonCopy from '~/components/ui/ButtonCopy';
import BSCPaginator from '~/components/ui/BSCPaginator';

Vue.component('ctm-modal', CtmModal);
Vue.component('base-btn', BaseButton);
Vue.component('base-field', BaseInput);
Vue.component('base-dd', BaseDD);
Vue.component('base-checkbox', BaseCheckbox);
Vue.component('loader', Loader);
Vue.component('base-pager', BasePager);
Vue.component('search-filter', SearchFilterField);
Vue.component('overview', Overview);
Vue.component('more-info', MoreInfo);
Vue.component('table-txs', TableTxs);
Vue.component('table-tokens', TableTokens);
Vue.component('table-blocks', TableBlocks);
Vue.component('info-item', InfoItem);
Vue.component('empty-data', EmptyData);
Vue.component('contract-info', ContractInfo);
Vue.component('contract-input', ContractInput);
Vue.component('button-copy', ButtonCopy);
Vue.component('paginator', BSCPaginator);
